# Dataset Properties
Before Starting, it would probably be beneficial to take a quick look at what exactly our database even is. I know its a 106 column, 206 MB Gargantuan CSV, but what is there to know?
> This is also basic familizarization with numpy and pandas which probably helps...

In [1]:
# Let's First Import this thing
import numpy as np
import pandas as pd

dataframe = pd.read_csv('./history.csv')

C:\Users\andyc\AppData\Local\Temp\ipykernel_146948\3847166104.py:5: DtypeWarning: Columns (87) have mixed types. Specify dtype option on import or set low_memory=False.
  dataframe = pd.read_csv('./history.csv')

In [29]:
# This tells us the rows x columns we are dealing with. Damn!
print(dataframe.shape)
dataframe.head(10)

(673339, 106)

,id,type_code,is_registered,country_code,currency_code,is_active,class_id,debit_code,last_trade_date,contract_type,...,is_hrdc_resp,is_plan_grandfathered,resp_specimen_plan,inserted_at,updated_at,is_olob,retail_last_maintenance_time,retail_last_maintenance_user,visible_in_reports,label
0,893724,CASH SWEEP,f,NaN,CAD,t,3.0,0,NaN,NaN,...,NaN,NaN,NaN,2023-05-30 14:20:18.531115+00,2023-08-08 18:53:01.439561+00,f,NaN,NaN,f,Churn
1,1268094,RRIF,t,NaN,CAD,t,5.0,C,2022-07-04,18.0,...,f,f,NaN,2023-05-30 14:20:18.531115+00,2023-08-10 21:47:25.370403+00,f,2023-01-03 00:00:00,BATCH,t,Churn
2,606613,SPOUSAL RRSP,t,NaN,CAD,t,5.0,A,2018-07-05,16.0,...,f,f,NaN,2023-05-30 14:20:18.531115+00,2023-08-10 21:47:25.370403+00,f,2018-07-17 00:00:00,GUERINO,f,Churn
3,741930,CASH,f,NaN,CAD,t,3.0,T,NaN,12.0,...,NaN,NaN,NaN,2023-05-30 14:20:18.531115+00,2023-08-08 18:53:01.439561+00,f,NaN,NaN,t,Churn
4,1137922,CASH,f,NaN,CAD,t,3.0,T,NaN,17.0,...,NaN,NaN,NaN,2023-05-30 14:20:18.531115+00,2023-08-08 20:52:08.352646+00,f,NaN,NaN,f,Churn
5,1020597,REG RRSP,t,NaN,CAD,t,5.0,C,2021-09-10,9.0,...,f,f,NaN,2023-05-30 14:20:18.531115+00,2023-08-10 21:47:25.370403+00,f,2019-10-02 00:00:00,BATCH,t,Churn
6,664230,CASH,f,NaN,CAD,t,3.0,T,NaN,9.0,...,NaN,NaN,NaN,2023-05-30 14:20:18.531115+00,2023-08-08 18:53:01.439561+00,f,NaN,NaN,t,Churn
7,763789,RESP,t,NaN,CAD,t,5.0,C,2023-03-15,17.0,...,t,f,1008002.0,2023-05-30 14:20:18.531115+00,2023-08-10 21:47:25.370403+00,f,2023-04-03 00:00:00,BATCH,t,Churn
8,1124157,TFSA,t,NaN,CAD,t,5.0,C,2021-02-16,12.0,...,f,f,NaN,2023-05-30 14:20:18.531115+00,2023-08-10 23:35:47.440886+00,f,2023-05-19 00:00:00,SUMRAS,t,Churn
9,740778,CASH,f,NaN,CAD,t,3.0,T,2021-10-26,8.0,...,NaN,NaN,NaN,2023-05-30 14:20:18.531115+00,2023-08-08 18:53:01.439561+00,f,NaN,NaN,t,Churn

In [7]:
# What are the columns?
for column in dataframe.columns:
    print(column)

id
type_code
is_registered
country_code
currency_code
is_active
class_id
debit_code
last_trade_date
contract_type
inception_date
net_of_fees
cashflows_custody_fee
fee_paid_separately
custody_fee_withdrawal
is_fee_exempt
branch
include_client_consolidation
use_client_address
credit_limit_type
retail_plan
is_spousal
is_arp_locked
arp_pension_origin
language_code
dividend_confirm_code
sss_location
options_trading_type
sss_type
sss_agent
is_midwest_clearing_account
rep_commission_rate
rep_commission_override
interest_dividend_conversion_type
guarantee_gtor_type
use_hand_delivery
use_mail
share_name_address_to_issuer
shareholder_instructions_received
rrsp_limit_reached
is_portfolio_account
has_no_min_commission
is_tms_eligible
is_agent_bbs_participant
is_parameters_account
is_spousal_transfer
spousal_age_flag
terminal_code
has_multiple_name
deceased_fair_market_value
target_grantor_grantee_flag
discretionary_trading_authorized
iso_funds_code
esir_number
shareholder_language
dup_trip_quad_code
special_tag
conjunction
title
function_code
tms_settlement_location
portfolio_cost_method
portfolio_name_address_option
portfolio_report_option
portfolio_summary_option
receive_general_mailings
loan_limit_override
interactive_portfolio_code
non_plan_book_value_flag
has_discrete_auth
last_update_date
is_non_objecting_beneficial_owner
is_objecting_to_disclose_info
mailing_consent
consent_to_pay_for_mail
consent_to_email_delivery
has_received_instruction
risk_tolerance
investment_objective
is_broker_account
is_inventory_account
is_gl_account
is_control_account
is_extract_eligible
last_maintenance_time
last_maintenance_user
is_pledged
special_fee_code
non_calendar_year_end
plan_effective_date
plan_end_date
is_resp
number_of_beneficiaries
rrif_original_date
use_original_date_for_payment_calc
is_family_resp
is_hrdc_resp
is_plan_grandfathered
resp_specimen_plan
inserted_at
updated_at
is_olob
retail_last_maintenance_time
retail_last_maintenance_user
visible_in_reports
label

In [10]:
# Here are a few of the bigger Categorical Data Items
grouping = dataframe.groupby(['type_code', 'label']).id.agg('count')
print(grouping)
print(grouping.agg('sum'))

type_code       label
CASH            Churn       190799
                No Churn        12
CASH SWEEP      Churn        80296
                No Churn        11
CASHA           Churn          248
                No Churn         1
COD             Churn         7748
HEDGE           Churn           30
HYPOTHECATED    Churn          445
LIF/RLIF/LRIF   Churn            6
                No Churn         5
LIRA            Churn          263
                No Churn       150
LIRA/LRSP/RLSP  Churn        16201
                No Churn     12089
MISSING         Churn         3198
MRGN            Churn        32089
                No Churn        26
OFFBOOK         Churn         7984
                No Churn      3998
RDSP            Churn          931
                No Churn       206
REG RRSP        Churn        65843
                No Churn     48375
RESP            Churn        13663
                No Churn      9063
RRIF            Churn        26281
                No Churn     12621
SHORT           Churn         1583
                No Churn         1
SPOUSAL RRIF    Churn         6149
                No Churn      2829
SPOUSAL RRSP    Churn        11453
                No Churn     10432
TFSA            Churn        72998
                No Churn     35075
Name: id, dtype: int64
673102

In [5]:
# Here are a few of the bigger Categorical Data Items
grouping = dataframe.groupby(['is_registered', 'label']).id.agg('count')
print(grouping)
print(grouping.agg('sum'))

is_registered  label
f              Churn       324656
               No Churn      4050
t              Churn       213788
               No Churn    130845
Name: id, dtype: int64
673339